# Generated by Django 5.2 on 2025-06-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='end_date',
            field=models.DateTimeField(unique=True),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='start_date',
            field=models.DateTimeField(unique=True),
        ),
    ]
